apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dashboard-db
type: Opaque
data:
  # postgres:password (base64)
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
  database: ZGFzaGJvYXJk
