apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-api-sa
  namespace: dashboard-app
  labels:
    app: dashboard-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dashboard-app
  name: dashboard-api-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-api-binding
  namespace: dashboard-app
subjects:
- kind: ServiceAccount
  name: dashboard-api-sa
  namespace: dashboard-app
roleRef:
  kind: Role
  name: dashboard-api-role
  apiGroup: rbac.authorization.k8s.io
